---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgress-deployment
  labels:
    app: postgress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
      volumes:
        - name: nextcloudVolume
          persistentvolumeclaim:
            claimName: ebs-claim
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: postgresUser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: postgresPassword
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: postgresDb
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    targetPort: 5432
    port: 5432