apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
type: Opaque
data:
    postgresUser: dXNlcm5hbWU=
    postgresPassword: cGFzc3dvcmQ=
    postgresDb: bmV4dGNsb3Vk
    nextcloudUser: dXNlcm5hbWU=
    nextcloudPassword: cGFzc3dvcmQ=